name: 'Build and Run Java Load Test'

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  ARTIFACT_REPO: k6-load-test-repo
  IMAGE_NAME: java-load-tester # Change the image name to java-load-tester

jobs:
  build-and-push-image:
    name: 'Build and Push Java Native Image'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # The context is now the root of the entire repository
          file: ./Dockerfile # Explicitly specify the path to the Dockerfile
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  run-load-test:
    name: 'Run Java Load Test Job'
    needs: build-and-push-image # Wait for the image build to complete
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Update Cloud Run Job with new image and run
        run: |
          gcloud run jobs execute java-load-test-job \
            --region ${{ env.GCP_REGION }} \
            --update-env-vars="TARGET_URL=${{ secrets.TARGET_URL_FOR_TEST }}" \
            --update-labels="commit-sha=${{ github.sha }}" \
            --tasks=50 \
            --wait
            # Note: The --args parameter is no longer needed here
